#!/usr/bin/env bash

if [ $# -eq 1 ]; then
    dom="www.$1 lb-01.$1 web-01.$1 web-02.$1"
else
    dom="$2.$1"
fi

dig $dom | awk '/ANSWER SECTION:/{getline; split($1,b,","); subdomain=b[1]; sub(".*\.", "", subdomain); print "The subdomain", subdomain, "is a", $4, "record and point to", $5}'
