#!/usr/bin/env bash
# This script install and configures Nginx to return "Hello World"

apt-get update -y

apt-get install  nginx -y

sudo ufw allow "Nginx HTTP"

sh -c "echo 'Hello World' > /var/www/html/index.html"

#Restart ngnix 
service ngnix restart
