#!/usr/bin/env bash
# This script installs and configures Nginx to return "Hello World"

# Update package lists and install Nginx
apt-get update -y
apt-get install nginx -y

# Allow HTTP traffic through UFW
ufw allow 'Nginx HTTP'

# Create a simple index.html file with "Hello World"
echo "Hello World!" | sudo tee /var/www/html/index.html

# start Nginx
service nginx start
