#!/usr/bin/env bash
# This script installs and configures Nginx to have a custom 404 page
# that contains the string "Ceci n'est pas une page."

# Exit immediately if a command exits with a non-zero status
set -e

# Check if nginx is installed
if [ ! -e /usr/sbin/nginx ]; then
    apt-get update
    apt-get -y install nginx
    echo "Nginx installed successfully."
else
    echo "Nginx is already installed."
fi

# Ensure that the directory is present.
if [ ! -e /var/www/html ]; then
    mkdir -p /var/www/html
fi

# Prepare the custom file
echo "Ceci n'est pas une page" > /var/www/html/404.html
echo "Hello World!" > /var/www/html/index.html

# Configure Nginx
cat <<EOF > /etc/nginx/sites-available/default
server {
    listen 80 default_server;
    listen [::]:80 default_server;

    root /var/www/html;

    location / {
        try_files \$uri \$uri/ =404;
    }

    location /redirect_me {
        return 301 https://youtube.com/;
    }

    error_page 404 /404.html;

    location = /404.html {
        internal;
    }
}
EOF

# Restart Nginx to apply the changes
service nginx restart
echo "Nginx configured with custom 404 page successfully."
