#!/usr/bin/env bash
# This script installs and configures Nginx to return "Hello World" and set up a 301 redirection from /redirect_me

# Exit immediately if a command exits with a non-zero status
set -e

# Update package lists and install Nginx
apt-get update -y
apt-get install nginx -y

# Allow HTTP traffic through UFW
ufw allow 'Nginx HTTP'

# Create a simple index.html file with "Hello World"
echo "Hello World!" | tee /var/www/html/index.html

# Create a custom 404 page
echo "Ceci n'est pas une page" | tee /var/www/html/404.html

# Use sed to configure Nginx to redirect /redirect_me to another page and set up a custom 404 error page
sed -i '/^\s*location \/ {/a\\n    location \/redirect_me {\n        return 301 https:\/\/www.youtube.com\/watch?v=QH2-TGUlwu4;\n    }\n\n    error_page 404 \/404.html;\n    location \/404.html {\n        root \/var\/www\/html;\n    }\n' /etc/nginx/sites-available/default

# Restart Nginx to apply the changes
systemctl restart nginx
