#!/usr/bin/env bash
# Install and configure HAProxy to load balance between web-01 and web-02

# Update packages and install HAProxy
apt-get update
apt-get -y install haproxy

# Configure HAProxy
cat << EOF > /etc/haproxy/haproxy.cfg
global
    log /dev/log    local0
    log /dev/log    local1 notice
    chroot /var/lib/haproxy
    stats socket /run/haproxy/admin.sock mode 660 level admin
    stats timeout 30s
    user haproxy
    group haproxy
    daemon

defaults
    log global
    mode http
    option httplog
    option dontlognull
    timeout connect 5000
    timeout client 50000
    timeout server 50000

frontend http_front
    bind *:80
    default_backend http_back

backend http_back
    balance roundrobin
    server 149664-web-01 18.204.9.159:80 check
    server 149664-web-02 54.157.167.38:80 check
EOF

# Ensure hostnames are configured correctly in /etc/hosts
echo "18.204.9.159 149664-web-01" >> /etc/hosts
echo "54.157.167.38 149664-web-02" >> /etc/hosts

# Restart HAProxy to apply changes
service haproxy restart

echo "HAProxy installed and configured successfully."
