#!/usr/bin/env bash
# Display lines containing the 'bash' word to get the PID of the Bash process

# shellcheck disable=SC2009
# Using ps command to list processes and grep to filter lines containing 'bash'

./1-list_your_processes | grep "bash"
