#!/usr/bin/env bash
#This script uses while loop to iterate on the 9th iteration, displays Best School and then Hi on a new line

counter=0

while [ $counter -lt 10 ]
do 
	if [ $counter -eq 9 ]
	then
		echo "Hi"
	fi
	echo "Best School"
	(( counter++ ))
done	
