#!/usr/bin/env bash
# This script configures Nginx to run as the nginx user and listen on port 8080
sudo sed -i 's/user www-data/user nginx' /etc/nginx/ngnix.conf
sudo sed -i 's/80/8080/g' /etc/ngnix/sites-available/default
sudo chmod 644 /etc/nginx/ngnix.conf
pkill apach2
sudo -u nginx service nginx restart
